// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/client/accounts"
	"github.com/mgazza/go-octopus-energy/client/electricity_meter_points"
	"github.com/mgazza/go-octopus-energy/client/gas_meter_points"
	"github.com/mgazza/go-octopus-energy/client/industry"
	"github.com/mgazza/go-octopus-energy/client/ivr_support"
	"github.com/mgazza/go-octopus-energy/client/products"
	"github.com/mgazza/go-octopus-energy/client/quotes"
	"github.com/mgazza/go-octopus-energy/client/voice"
)

// Default octopus energy r e s t API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.octopus.energy"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new octopus energy r e s t API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *OctopusEnergyRESTAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new octopus energy r e s t API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *OctopusEnergyRESTAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new octopus energy r e s t API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *OctopusEnergyRESTAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(OctopusEnergyRESTAPI)
	cli.Transport = transport
	cli.Accounts = accounts.New(transport, formats)
	cli.ElectricityMeterPoints = electricity_meter_points.New(transport, formats)
	cli.GasMeterPoints = gas_meter_points.New(transport, formats)
	cli.Industry = industry.New(transport, formats)
	cli.IvrSupport = ivr_support.New(transport, formats)
	cli.Products = products.New(transport, formats)
	cli.Quotes = quotes.New(transport, formats)
	cli.Voice = voice.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// OctopusEnergyRESTAPI is a client for octopus energy r e s t API
type OctopusEnergyRESTAPI struct {
	Accounts accounts.ClientService

	ElectricityMeterPoints electricity_meter_points.ClientService

	GasMeterPoints gas_meter_points.ClientService

	Industry industry.ClientService

	IvrSupport ivr_support.ClientService

	Products products.ClientService

	Quotes quotes.ClientService

	Voice voice.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *OctopusEnergyRESTAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Accounts.SetTransport(transport)
	c.ElectricityMeterPoints.SetTransport(transport)
	c.GasMeterPoints.SetTransport(transport)
	c.Industry.SetTransport(transport)
	c.IvrSupport.SetTransport(transport)
	c.Products.SetTransport(transport)
	c.Quotes.SetTransport(transport)
	c.Voice.SetTransport(transport)
}
