// Code generated by go-swagger; DO NOT EDIT.

package quotes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// NewCreateaQuoteParams creates a new CreateaQuoteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateaQuoteParams() *CreateaQuoteParams {
	return &CreateaQuoteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateaQuoteParamsWithTimeout creates a new CreateaQuoteParams object
// with the ability to set a timeout on a request.
func NewCreateaQuoteParamsWithTimeout(timeout time.Duration) *CreateaQuoteParams {
	return &CreateaQuoteParams{
		timeout: timeout,
	}
}

// NewCreateaQuoteParamsWithContext creates a new CreateaQuoteParams object
// with the ability to set a context for a request.
func NewCreateaQuoteParamsWithContext(ctx context.Context) *CreateaQuoteParams {
	return &CreateaQuoteParams{
		Context: ctx,
	}
}

// NewCreateaQuoteParamsWithHTTPClient creates a new CreateaQuoteParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateaQuoteParamsWithHTTPClient(client *http.Client) *CreateaQuoteParams {
	return &CreateaQuoteParams{
		HTTPClient: client,
	}
}

/*
CreateaQuoteParams contains all the parameters to send to the API endpoint

	for the create a quote operation.

	Typically these are written to a http.Request.
*/
type CreateaQuoteParams struct {

	// Body.
	Body *models.Create

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create a quote params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateaQuoteParams) WithDefaults() *CreateaQuoteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create a quote params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateaQuoteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create a quote params
func (o *CreateaQuoteParams) WithTimeout(timeout time.Duration) *CreateaQuoteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create a quote params
func (o *CreateaQuoteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create a quote params
func (o *CreateaQuoteParams) WithContext(ctx context.Context) *CreateaQuoteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create a quote params
func (o *CreateaQuoteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create a quote params
func (o *CreateaQuoteParams) WithHTTPClient(client *http.Client) *CreateaQuoteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create a quote params
func (o *CreateaQuoteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create a quote params
func (o *CreateaQuoteParams) WithBody(body *models.Create) *CreateaQuoteParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create a quote params
func (o *CreateaQuoteParams) SetBody(body *models.Create) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateaQuoteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
