// Code generated by go-swagger; DO NOT EDIT.

package quotes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// CreateaQuoteReader is a Reader for the CreateaQuote structure.
type CreateaQuoteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateaQuoteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateAQuoteCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateAQuoteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/quotes/] Create a quote", response, response.Code())
	}
}

// NewCreateAQuoteCreated creates a CreateAQuoteCreated with default headers values
func NewCreateAQuoteCreated() *CreateAQuoteCreated {
	return &CreateAQuoteCreated{}
}

/*
CreateAQuoteCreated describes a response with status code 201, with default header values.

The quote has been created
*/
type CreateAQuoteCreated struct {
	Payload *models.QuoteCreated
}

// IsSuccess returns true when this create a quote created response has a 2xx status code
func (o *CreateAQuoteCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create a quote created response has a 3xx status code
func (o *CreateAQuoteCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create a quote created response has a 4xx status code
func (o *CreateAQuoteCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create a quote created response has a 5xx status code
func (o *CreateAQuoteCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create a quote created response a status code equal to that given
func (o *CreateAQuoteCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create a quote created response
func (o *CreateAQuoteCreated) Code() int {
	return 201
}

func (o *CreateAQuoteCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/quotes/][%d] createAQuoteCreated %s", 201, payload)
}

func (o *CreateAQuoteCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/quotes/][%d] createAQuoteCreated %s", 201, payload)
}

func (o *CreateAQuoteCreated) GetPayload() *models.QuoteCreated {
	return o.Payload
}

func (o *CreateAQuoteCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.QuoteCreated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAQuoteBadRequest creates a CreateAQuoteBadRequest with default headers values
func NewCreateAQuoteBadRequest() *CreateAQuoteBadRequest {
	return &CreateAQuoteBadRequest{}
}

/*
CreateAQuoteBadRequest describes a response with status code 400, with default header values.

Validation errors. The error response payload will take the same field structure as the request payload.
*/
type CreateAQuoteBadRequest struct {
	Payload *models.CreateQuoteError
}

// IsSuccess returns true when this create a quote bad request response has a 2xx status code
func (o *CreateAQuoteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create a quote bad request response has a 3xx status code
func (o *CreateAQuoteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create a quote bad request response has a 4xx status code
func (o *CreateAQuoteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create a quote bad request response has a 5xx status code
func (o *CreateAQuoteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create a quote bad request response a status code equal to that given
func (o *CreateAQuoteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create a quote bad request response
func (o *CreateAQuoteBadRequest) Code() int {
	return 400
}

func (o *CreateAQuoteBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/quotes/][%d] createAQuoteBadRequest %s", 400, payload)
}

func (o *CreateAQuoteBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/quotes/][%d] createAQuoteBadRequest %s", 400, payload)
}

func (o *CreateAQuoteBadRequest) GetPayload() *models.CreateQuoteError {
	return o.Payload
}

func (o *CreateAQuoteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateQuoteError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
