// Code generated by go-swagger; DO NOT EDIT.

package electricity_meter_points

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// GetElectricityMeterPointReader is a Reader for the GetElectricityMeterPoint structure.
type GetElectricityMeterPointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetElectricityMeterPointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetElectricityMeterPointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/electricity-meter-points/{mpan}/] Get Electricity Meter Point", response, response.Code())
	}
}

// NewGetElectricityMeterPointOK creates a GetElectricityMeterPointOK with default headers values
func NewGetElectricityMeterPointOK() *GetElectricityMeterPointOK {
	return &GetElectricityMeterPointOK{}
}

/*
GetElectricityMeterPointOK describes a response with status code 200, with default header values.

GetElectricityMeterPointOK get electricity meter point o k
*/
type GetElectricityMeterPointOK struct {
	Payload *models.ElectricityMeterPoint
}

// IsSuccess returns true when this get electricity meter point o k response has a 2xx status code
func (o *GetElectricityMeterPointOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get electricity meter point o k response has a 3xx status code
func (o *GetElectricityMeterPointOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get electricity meter point o k response has a 4xx status code
func (o *GetElectricityMeterPointOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get electricity meter point o k response has a 5xx status code
func (o *GetElectricityMeterPointOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get electricity meter point o k response a status code equal to that given
func (o *GetElectricityMeterPointOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get electricity meter point o k response
func (o *GetElectricityMeterPointOK) Code() int {
	return 200
}

func (o *GetElectricityMeterPointOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/electricity-meter-points/{mpan}/][%d] getElectricityMeterPointOK %s", 200, payload)
}

func (o *GetElectricityMeterPointOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/electricity-meter-points/{mpan}/][%d] getElectricityMeterPointOK %s", 200, payload)
}

func (o *GetElectricityMeterPointOK) GetPayload() *models.ElectricityMeterPoint {
	return o.Payload
}

func (o *GetElectricityMeterPointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ElectricityMeterPoint)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
