// Code generated by go-swagger; DO NOT EDIT.

package electricity_meter_points

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// ListConsumptionForAnElectricityMeterReader is a Reader for the ListConsumptionForAnElectricityMeter structure.
type ListConsumptionForAnElectricityMeterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListConsumptionForAnElectricityMeterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListConsumptionForAnElectricityMeterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/electricity-meter-points/{mpan}/meters/{serial_number}/consumption/] List consumption for an electricity meter", response, response.Code())
	}
}

// NewListConsumptionForAnElectricityMeterOK creates a ListConsumptionForAnElectricityMeterOK with default headers values
func NewListConsumptionForAnElectricityMeterOK() *ListConsumptionForAnElectricityMeterOK {
	return &ListConsumptionForAnElectricityMeterOK{}
}

/*
ListConsumptionForAnElectricityMeterOK describes a response with status code 200, with default header values.

ListConsumptionForAnElectricityMeterOK list consumption for an electricity meter o k
*/
type ListConsumptionForAnElectricityMeterOK struct {
	Payload *models.PaginatedConsumptionList
}

// IsSuccess returns true when this list consumption for an electricity meter o k response has a 2xx status code
func (o *ListConsumptionForAnElectricityMeterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list consumption for an electricity meter o k response has a 3xx status code
func (o *ListConsumptionForAnElectricityMeterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list consumption for an electricity meter o k response has a 4xx status code
func (o *ListConsumptionForAnElectricityMeterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list consumption for an electricity meter o k response has a 5xx status code
func (o *ListConsumptionForAnElectricityMeterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list consumption for an electricity meter o k response a status code equal to that given
func (o *ListConsumptionForAnElectricityMeterOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list consumption for an electricity meter o k response
func (o *ListConsumptionForAnElectricityMeterOK) Code() int {
	return 200
}

func (o *ListConsumptionForAnElectricityMeterOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/electricity-meter-points/{mpan}/meters/{serial_number}/consumption/][%d] listConsumptionForAnElectricityMeterOK %s", 200, payload)
}

func (o *ListConsumptionForAnElectricityMeterOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/electricity-meter-points/{mpan}/meters/{serial_number}/consumption/][%d] listConsumptionForAnElectricityMeterOK %s", 200, payload)
}

func (o *ListConsumptionForAnElectricityMeterOK) GetPayload() *models.PaginatedConsumptionList {
	return o.Payload
}

func (o *ListConsumptionForAnElectricityMeterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedConsumptionList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
