// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// ListGasTariffStandardUnitRatesReader is a Reader for the ListGasTariffStandardUnitRates structure.
type ListGasTariffStandardUnitRatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListGasTariffStandardUnitRatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListGasTariffStandardUnitRatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/products/{product_code}/gas-tariffs/{tariff_code}/standard-unit-rates/] List Gas Tariff Standard Unit Rates", response, response.Code())
	}
}

// NewListGasTariffStandardUnitRatesOK creates a ListGasTariffStandardUnitRatesOK with default headers values
func NewListGasTariffStandardUnitRatesOK() *ListGasTariffStandardUnitRatesOK {
	return &ListGasTariffStandardUnitRatesOK{}
}

/*
ListGasTariffStandardUnitRatesOK describes a response with status code 200, with default header values.

ListGasTariffStandardUnitRatesOK list gas tariff standard unit rates o k
*/
type ListGasTariffStandardUnitRatesOK struct {
	Payload *models.PaginatedHistoricalChargeList
}

// IsSuccess returns true when this list gas tariff standard unit rates o k response has a 2xx status code
func (o *ListGasTariffStandardUnitRatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list gas tariff standard unit rates o k response has a 3xx status code
func (o *ListGasTariffStandardUnitRatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list gas tariff standard unit rates o k response has a 4xx status code
func (o *ListGasTariffStandardUnitRatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list gas tariff standard unit rates o k response has a 5xx status code
func (o *ListGasTariffStandardUnitRatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list gas tariff standard unit rates o k response a status code equal to that given
func (o *ListGasTariffStandardUnitRatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list gas tariff standard unit rates o k response
func (o *ListGasTariffStandardUnitRatesOK) Code() int {
	return 200
}

func (o *ListGasTariffStandardUnitRatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/products/{product_code}/gas-tariffs/{tariff_code}/standard-unit-rates/][%d] listGasTariffStandardUnitRatesOK %s", 200, payload)
}

func (o *ListGasTariffStandardUnitRatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/products/{product_code}/gas-tariffs/{tariff_code}/standard-unit-rates/][%d] listGasTariffStandardUnitRatesOK %s", 200, payload)
}

func (o *ListGasTariffStandardUnitRatesOK) GetPayload() *models.PaginatedHistoricalChargeList {
	return o.Payload
}

func (o *ListGasTariffStandardUnitRatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedHistoricalChargeList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
