// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// ListElectricityTariffStandardUnitRatesReader is a Reader for the ListElectricityTariffStandardUnitRates structure.
type ListElectricityTariffStandardUnitRatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListElectricityTariffStandardUnitRatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListElectricityTariffStandardUnitRatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/products/{product_code}/electricity-tariffs/{tariff_code}/standard-unit-rates/] List Electricity Tariff Standard Unit Rates", response, response.Code())
	}
}

// NewListElectricityTariffStandardUnitRatesOK creates a ListElectricityTariffStandardUnitRatesOK with default headers values
func NewListElectricityTariffStandardUnitRatesOK() *ListElectricityTariffStandardUnitRatesOK {
	return &ListElectricityTariffStandardUnitRatesOK{}
}

/*
ListElectricityTariffStandardUnitRatesOK describes a response with status code 200, with default header values.

ListElectricityTariffStandardUnitRatesOK list electricity tariff standard unit rates o k
*/
type ListElectricityTariffStandardUnitRatesOK struct {
	Payload *models.PaginatedHistoricalChargeList
}

// IsSuccess returns true when this list electricity tariff standard unit rates o k response has a 2xx status code
func (o *ListElectricityTariffStandardUnitRatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list electricity tariff standard unit rates o k response has a 3xx status code
func (o *ListElectricityTariffStandardUnitRatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list electricity tariff standard unit rates o k response has a 4xx status code
func (o *ListElectricityTariffStandardUnitRatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list electricity tariff standard unit rates o k response has a 5xx status code
func (o *ListElectricityTariffStandardUnitRatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list electricity tariff standard unit rates o k response a status code equal to that given
func (o *ListElectricityTariffStandardUnitRatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list electricity tariff standard unit rates o k response
func (o *ListElectricityTariffStandardUnitRatesOK) Code() int {
	return 200
}

func (o *ListElectricityTariffStandardUnitRatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/products/{product_code}/electricity-tariffs/{tariff_code}/standard-unit-rates/][%d] listElectricityTariffStandardUnitRatesOK %s", 200, payload)
}

func (o *ListElectricityTariffStandardUnitRatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/products/{product_code}/electricity-tariffs/{tariff_code}/standard-unit-rates/][%d] listElectricityTariffStandardUnitRatesOK %s", 200, payload)
}

func (o *ListElectricityTariffStandardUnitRatesOK) GetPayload() *models.PaginatedHistoricalChargeList {
	return o.Payload
}

func (o *ListElectricityTariffStandardUnitRatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedHistoricalChargeList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
