// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// ListElectricityTariffStandingChargesReader is a Reader for the ListElectricityTariffStandingCharges structure.
type ListElectricityTariffStandingChargesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListElectricityTariffStandingChargesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListElectricityTariffStandingChargesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/products/{product_code}/electricity-tariffs/{tariff_code}/standing-charges/] List Electricity Tariff Standing Charges", response, response.Code())
	}
}

// NewListElectricityTariffStandingChargesOK creates a ListElectricityTariffStandingChargesOK with default headers values
func NewListElectricityTariffStandingChargesOK() *ListElectricityTariffStandingChargesOK {
	return &ListElectricityTariffStandingChargesOK{}
}

/*
ListElectricityTariffStandingChargesOK describes a response with status code 200, with default header values.

ListElectricityTariffStandingChargesOK list electricity tariff standing charges o k
*/
type ListElectricityTariffStandingChargesOK struct {
	Payload *models.PaginatedHistoricalChargeList
}

// IsSuccess returns true when this list electricity tariff standing charges o k response has a 2xx status code
func (o *ListElectricityTariffStandingChargesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list electricity tariff standing charges o k response has a 3xx status code
func (o *ListElectricityTariffStandingChargesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list electricity tariff standing charges o k response has a 4xx status code
func (o *ListElectricityTariffStandingChargesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list electricity tariff standing charges o k response has a 5xx status code
func (o *ListElectricityTariffStandingChargesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list electricity tariff standing charges o k response a status code equal to that given
func (o *ListElectricityTariffStandingChargesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list electricity tariff standing charges o k response
func (o *ListElectricityTariffStandingChargesOK) Code() int {
	return 200
}

func (o *ListElectricityTariffStandingChargesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/products/{product_code}/electricity-tariffs/{tariff_code}/standing-charges/][%d] listElectricityTariffStandingChargesOK %s", 200, payload)
}

func (o *ListElectricityTariffStandingChargesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/products/{product_code}/electricity-tariffs/{tariff_code}/standing-charges/][%d] listElectricityTariffStandingChargesOK %s", 200, payload)
}

func (o *ListElectricityTariffStandingChargesOK) GetPayload() *models.PaginatedHistoricalChargeList {
	return o.Payload
}

func (o *ListElectricityTariffStandingChargesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedHistoricalChargeList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
