// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListGasTariffStandardUnitRatesParams creates a new ListGasTariffStandardUnitRatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListGasTariffStandardUnitRatesParams() *ListGasTariffStandardUnitRatesParams {
	return &ListGasTariffStandardUnitRatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListGasTariffStandardUnitRatesParamsWithTimeout creates a new ListGasTariffStandardUnitRatesParams object
// with the ability to set a timeout on a request.
func NewListGasTariffStandardUnitRatesParamsWithTimeout(timeout time.Duration) *ListGasTariffStandardUnitRatesParams {
	return &ListGasTariffStandardUnitRatesParams{
		timeout: timeout,
	}
}

// NewListGasTariffStandardUnitRatesParamsWithContext creates a new ListGasTariffStandardUnitRatesParams object
// with the ability to set a context for a request.
func NewListGasTariffStandardUnitRatesParamsWithContext(ctx context.Context) *ListGasTariffStandardUnitRatesParams {
	return &ListGasTariffStandardUnitRatesParams{
		Context: ctx,
	}
}

// NewListGasTariffStandardUnitRatesParamsWithHTTPClient creates a new ListGasTariffStandardUnitRatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListGasTariffStandardUnitRatesParamsWithHTTPClient(client *http.Client) *ListGasTariffStandardUnitRatesParams {
	return &ListGasTariffStandardUnitRatesParams{
		HTTPClient: client,
	}
}

/*
ListGasTariffStandardUnitRatesParams contains all the parameters to send to the API endpoint

	for the list gas tariff standard unit rates operation.

	Typically these are written to a http.Request.
*/
type ListGasTariffStandardUnitRatesParams struct {

	/* Page.

	   A page number within the paginated result set.
	*/
	Page *int64

	/* PageSize.

	   Page size of returned results. Default is 100, maximum is 1500 to give up to a month of half-hourly prices.
	*/
	PageSize *int64

	/* PeriodFrom.

	   Show results from the given datetime (inclusive). This parameter can be provided on its own.

	   Format: datetime
	*/
	PeriodFrom *strfmt.DateTime

	/* PeriodTo.

	   Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range.

	   Format: datetime
	*/
	PeriodTo *strfmt.DateTime

	/* ProductCode.

	   The code of the product to be retrieved, for example VAR-17-01-11.
	*/
	ProductCode string

	/* TariffCode.

	   The code of the tariff to be retrieved, for example E-1R-VAR-17-01-11-A.
	*/
	TariffCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list gas tariff standard unit rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListGasTariffStandardUnitRatesParams) WithDefaults() *ListGasTariffStandardUnitRatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list gas tariff standard unit rates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListGasTariffStandardUnitRatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithTimeout(timeout time.Duration) *ListGasTariffStandardUnitRatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithContext(ctx context.Context) *ListGasTariffStandardUnitRatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithHTTPClient(client *http.Client) *ListGasTariffStandardUnitRatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithPage(page *int64) *ListGasTariffStandardUnitRatesParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithPageSize(pageSize *int64) *ListGasTariffStandardUnitRatesParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithPeriodFrom adds the periodFrom to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithPeriodFrom(periodFrom *strfmt.DateTime) *ListGasTariffStandardUnitRatesParams {
	o.SetPeriodFrom(periodFrom)
	return o
}

// SetPeriodFrom adds the periodFrom to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetPeriodFrom(periodFrom *strfmt.DateTime) {
	o.PeriodFrom = periodFrom
}

// WithPeriodTo adds the periodTo to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithPeriodTo(periodTo *strfmt.DateTime) *ListGasTariffStandardUnitRatesParams {
	o.SetPeriodTo(periodTo)
	return o
}

// SetPeriodTo adds the periodTo to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetPeriodTo(periodTo *strfmt.DateTime) {
	o.PeriodTo = periodTo
}

// WithProductCode adds the productCode to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithProductCode(productCode string) *ListGasTariffStandardUnitRatesParams {
	o.SetProductCode(productCode)
	return o
}

// SetProductCode adds the productCode to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetProductCode(productCode string) {
	o.ProductCode = productCode
}

// WithTariffCode adds the tariffCode to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) WithTariffCode(tariffCode string) *ListGasTariffStandardUnitRatesParams {
	o.SetTariffCode(tariffCode)
	return o
}

// SetTariffCode adds the tariffCode to the list gas tariff standard unit rates params
func (o *ListGasTariffStandardUnitRatesParams) SetTariffCode(tariffCode string) {
	o.TariffCode = tariffCode
}

// WriteToRequest writes these params to a swagger request
func (o *ListGasTariffStandardUnitRatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param page_size
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("page_size", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.PeriodFrom != nil {

		// query param period_from
		var qrPeriodFrom strfmt.DateTime

		if o.PeriodFrom != nil {
			qrPeriodFrom = *o.PeriodFrom
		}
		qPeriodFrom := qrPeriodFrom.String()
		if qPeriodFrom != "" {

			if err := r.SetQueryParam("period_from", qPeriodFrom); err != nil {
				return err
			}
		}
	}

	if o.PeriodTo != nil {

		// query param period_to
		var qrPeriodTo strfmt.DateTime

		if o.PeriodTo != nil {
			qrPeriodTo = *o.PeriodTo
		}
		qPeriodTo := qrPeriodTo.String()
		if qPeriodTo != "" {

			if err := r.SetQueryParam("period_to", qPeriodTo); err != nil {
				return err
			}
		}
	}

	// path param product_code
	if err := r.SetPathParam("product_code", o.ProductCode); err != nil {
		return err
	}

	// path param tariff_code
	if err := r.SetPathParam("tariff_code", o.TariffCode); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
