// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRetrieveaProductParams creates a new RetrieveaProductParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRetrieveaProductParams() *RetrieveaProductParams {
	return &RetrieveaProductParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveaProductParamsWithTimeout creates a new RetrieveaProductParams object
// with the ability to set a timeout on a request.
func NewRetrieveaProductParamsWithTimeout(timeout time.Duration) *RetrieveaProductParams {
	return &RetrieveaProductParams{
		timeout: timeout,
	}
}

// NewRetrieveaProductParamsWithContext creates a new RetrieveaProductParams object
// with the ability to set a context for a request.
func NewRetrieveaProductParamsWithContext(ctx context.Context) *RetrieveaProductParams {
	return &RetrieveaProductParams{
		Context: ctx,
	}
}

// NewRetrieveaProductParamsWithHTTPClient creates a new RetrieveaProductParams object
// with the ability to set a custom HTTPClient for a request.
func NewRetrieveaProductParamsWithHTTPClient(client *http.Client) *RetrieveaProductParams {
	return &RetrieveaProductParams{
		HTTPClient: client,
	}
}

/*
RetrieveaProductParams contains all the parameters to send to the API endpoint

	for the retrieve a product operation.

	Typically these are written to a http.Request.
*/
type RetrieveaProductParams struct {

	/* ProductCode.

	   The code of the product to be retrieved, for example VAR-17-01-11.
	*/
	ProductCode string

	/* TariffsActiveAt.

	   The point in time in which to show the active charges. Defaults to current datetime.

	   Format: date-time
	*/
	TariffsActiveAt *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the retrieve a product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveaProductParams) WithDefaults() *RetrieveaProductParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the retrieve a product params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RetrieveaProductParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the retrieve a product params
func (o *RetrieveaProductParams) WithTimeout(timeout time.Duration) *RetrieveaProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve a product params
func (o *RetrieveaProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve a product params
func (o *RetrieveaProductParams) WithContext(ctx context.Context) *RetrieveaProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve a product params
func (o *RetrieveaProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve a product params
func (o *RetrieveaProductParams) WithHTTPClient(client *http.Client) *RetrieveaProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve a product params
func (o *RetrieveaProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProductCode adds the productCode to the retrieve a product params
func (o *RetrieveaProductParams) WithProductCode(productCode string) *RetrieveaProductParams {
	o.SetProductCode(productCode)
	return o
}

// SetProductCode adds the productCode to the retrieve a product params
func (o *RetrieveaProductParams) SetProductCode(productCode string) {
	o.ProductCode = productCode
}

// WithTariffsActiveAt adds the tariffsActiveAt to the retrieve a product params
func (o *RetrieveaProductParams) WithTariffsActiveAt(tariffsActiveAt *strfmt.DateTime) *RetrieveaProductParams {
	o.SetTariffsActiveAt(tariffsActiveAt)
	return o
}

// SetTariffsActiveAt adds the tariffsActiveAt to the retrieve a product params
func (o *RetrieveaProductParams) SetTariffsActiveAt(tariffsActiveAt *strfmt.DateTime) {
	o.TariffsActiveAt = tariffsActiveAt
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveaProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param product_code
	if err := r.SetPathParam("product_code", o.ProductCode); err != nil {
		return err
	}

	if o.TariffsActiveAt != nil {

		// query param tariffs_active_at
		var qrTariffsActiveAt strfmt.DateTime

		if o.TariffsActiveAt != nil {
			qrTariffsActiveAt = *o.TariffsActiveAt
		}
		qTariffsActiveAt := qrTariffsActiveAt.String()
		if qTariffsActiveAt != "" {

			if err := r.SetQueryParam("tariffs_active_at", qTariffsActiveAt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
