// Code generated by go-swagger; DO NOT EDIT.

package gas_meter_points

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// ListConsumptionForaGasMeterReader is a Reader for the ListConsumptionForaGasMeter structure.
type ListConsumptionForaGasMeterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListConsumptionForaGasMeterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListConsumptionForAGasMeterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/gas-meter-points/{mprn}/meters/{serial_number}/consumption/] List consumption for a gas meter", response, response.Code())
	}
}

// NewListConsumptionForAGasMeterOK creates a ListConsumptionForAGasMeterOK with default headers values
func NewListConsumptionForAGasMeterOK() *ListConsumptionForAGasMeterOK {
	return &ListConsumptionForAGasMeterOK{}
}

/*
ListConsumptionForAGasMeterOK describes a response with status code 200, with default header values.

ListConsumptionForAGasMeterOK list consumption for a gas meter o k
*/
type ListConsumptionForAGasMeterOK struct {
	Payload *models.PaginatedConsumptionList
}

// IsSuccess returns true when this list consumption for a gas meter o k response has a 2xx status code
func (o *ListConsumptionForAGasMeterOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list consumption for a gas meter o k response has a 3xx status code
func (o *ListConsumptionForAGasMeterOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list consumption for a gas meter o k response has a 4xx status code
func (o *ListConsumptionForAGasMeterOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list consumption for a gas meter o k response has a 5xx status code
func (o *ListConsumptionForAGasMeterOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list consumption for a gas meter o k response a status code equal to that given
func (o *ListConsumptionForAGasMeterOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list consumption for a gas meter o k response
func (o *ListConsumptionForAGasMeterOK) Code() int {
	return 200
}

func (o *ListConsumptionForAGasMeterOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/gas-meter-points/{mprn}/meters/{serial_number}/consumption/][%d] listConsumptionForAGasMeterOK %s", 200, payload)
}

func (o *ListConsumptionForAGasMeterOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/gas-meter-points/{mprn}/meters/{serial_number}/consumption/][%d] listConsumptionForAGasMeterOK %s", 200, payload)
}

func (o *ListConsumptionForAGasMeterOK) GetPayload() *models.PaginatedConsumptionList {
	return o.Payload
}

func (o *ListConsumptionForAGasMeterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedConsumptionList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
