// Code generated by go-swagger; DO NOT EDIT.

package voice

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TwilioEnqueueAudioReader is a Reader for the TwilioEnqueueAudio structure.
type TwilioEnqueueAudioReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TwilioEnqueueAudioReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTwilioEnqueueAudioOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/voice/twilio/enqueue-audio/] Twilio Enqueue Audio", response, response.Code())
	}
}

// NewTwilioEnqueueAudioOK creates a TwilioEnqueueAudioOK with default headers values
func NewTwilioEnqueueAudioOK() *TwilioEnqueueAudioOK {
	return &TwilioEnqueueAudioOK{}
}

/*
TwilioEnqueueAudioOK describes a response with status code 200, with default header values.

No response body
*/
type TwilioEnqueueAudioOK struct {
}

// IsSuccess returns true when this twilio enqueue audio o k response has a 2xx status code
func (o *TwilioEnqueueAudioOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this twilio enqueue audio o k response has a 3xx status code
func (o *TwilioEnqueueAudioOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this twilio enqueue audio o k response has a 4xx status code
func (o *TwilioEnqueueAudioOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this twilio enqueue audio o k response has a 5xx status code
func (o *TwilioEnqueueAudioOK) IsServerError() bool {
	return false
}

// IsCode returns true when this twilio enqueue audio o k response a status code equal to that given
func (o *TwilioEnqueueAudioOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the twilio enqueue audio o k response
func (o *TwilioEnqueueAudioOK) Code() int {
	return 200
}

func (o *TwilioEnqueueAudioOK) Error() string {
	return fmt.Sprintf("[POST /v1/voice/twilio/enqueue-audio/][%d] twilioEnqueueAudioOK", 200)
}

func (o *TwilioEnqueueAudioOK) String() string {
	return fmt.Sprintf("[POST /v1/voice/twilio/enqueue-audio/][%d] twilioEnqueueAudioOK", 200)
}

func (o *TwilioEnqueueAudioOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
