// Code generated by go-swagger; DO NOT EDIT.

package ivr_support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMinimalTwilioEnqueueParams creates a new MinimalTwilioEnqueueParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMinimalTwilioEnqueueParams() *MinimalTwilioEnqueueParams {
	return &MinimalTwilioEnqueueParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMinimalTwilioEnqueueParamsWithTimeout creates a new MinimalTwilioEnqueueParams object
// with the ability to set a timeout on a request.
func NewMinimalTwilioEnqueueParamsWithTimeout(timeout time.Duration) *MinimalTwilioEnqueueParams {
	return &MinimalTwilioEnqueueParams{
		timeout: timeout,
	}
}

// NewMinimalTwilioEnqueueParamsWithContext creates a new MinimalTwilioEnqueueParams object
// with the ability to set a context for a request.
func NewMinimalTwilioEnqueueParamsWithContext(ctx context.Context) *MinimalTwilioEnqueueParams {
	return &MinimalTwilioEnqueueParams{
		Context: ctx,
	}
}

// NewMinimalTwilioEnqueueParamsWithHTTPClient creates a new MinimalTwilioEnqueueParams object
// with the ability to set a custom HTTPClient for a request.
func NewMinimalTwilioEnqueueParamsWithHTTPClient(client *http.Client) *MinimalTwilioEnqueueParams {
	return &MinimalTwilioEnqueueParams{
		HTTPClient: client,
	}
}

/*
MinimalTwilioEnqueueParams contains all the parameters to send to the API endpoint

	for the minimal twilio enqueue operation.

	Typically these are written to a http.Request.
*/
type MinimalTwilioEnqueueParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the minimal twilio enqueue params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MinimalTwilioEnqueueParams) WithDefaults() *MinimalTwilioEnqueueParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the minimal twilio enqueue params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MinimalTwilioEnqueueParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the minimal twilio enqueue params
func (o *MinimalTwilioEnqueueParams) WithTimeout(timeout time.Duration) *MinimalTwilioEnqueueParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the minimal twilio enqueue params
func (o *MinimalTwilioEnqueueParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the minimal twilio enqueue params
func (o *MinimalTwilioEnqueueParams) WithContext(ctx context.Context) *MinimalTwilioEnqueueParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the minimal twilio enqueue params
func (o *MinimalTwilioEnqueueParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the minimal twilio enqueue params
func (o *MinimalTwilioEnqueueParams) WithHTTPClient(client *http.Client) *MinimalTwilioEnqueueParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the minimal twilio enqueue params
func (o *MinimalTwilioEnqueueParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *MinimalTwilioEnqueueParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
