// Code generated by go-swagger; DO NOT EDIT.

package ivr_support

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// MinimalTwilioEnqueueReader is a Reader for the MinimalTwilioEnqueue structure.
type MinimalTwilioEnqueueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MinimalTwilioEnqueueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMinimalTwilioEnqueueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/ivr-support/minimal-enqueue-for-incidents/] Minimal Twilio Enqueue", response, response.Code())
	}
}

// NewMinimalTwilioEnqueueOK creates a MinimalTwilioEnqueueOK with default headers values
func NewMinimalTwilioEnqueueOK() *MinimalTwilioEnqueueOK {
	return &MinimalTwilioEnqueueOK{}
}

/*
MinimalTwilioEnqueueOK describes a response with status code 200, with default header values.

No response body
*/
type MinimalTwilioEnqueueOK struct {
}

// IsSuccess returns true when this minimal twilio enqueue o k response has a 2xx status code
func (o *MinimalTwilioEnqueueOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this minimal twilio enqueue o k response has a 3xx status code
func (o *MinimalTwilioEnqueueOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this minimal twilio enqueue o k response has a 4xx status code
func (o *MinimalTwilioEnqueueOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this minimal twilio enqueue o k response has a 5xx status code
func (o *MinimalTwilioEnqueueOK) IsServerError() bool {
	return false
}

// IsCode returns true when this minimal twilio enqueue o k response a status code equal to that given
func (o *MinimalTwilioEnqueueOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the minimal twilio enqueue o k response
func (o *MinimalTwilioEnqueueOK) Code() int {
	return 200
}

func (o *MinimalTwilioEnqueueOK) Error() string {
	return fmt.Sprintf("[POST /v1/ivr-support/minimal-enqueue-for-incidents/][%d] minimalTwilioEnqueueOK", 200)
}

func (o *MinimalTwilioEnqueueOK) String() string {
	return fmt.Sprintf("[POST /v1/ivr-support/minimal-enqueue-for-incidents/][%d] minimalTwilioEnqueueOK", 200)
}

func (o *MinimalTwilioEnqueueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
