// Code generated by go-swagger; DO NOT EDIT.

package industry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// ListIndustryGridSupplyPointsReader is a Reader for the ListIndustryGridSupplyPoints structure.
type ListIndustryGridSupplyPointsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListIndustryGridSupplyPointsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListIndustryGridSupplyPointsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/industry/grid-supply-points/] List Industry Grid Supply Points", response, response.Code())
	}
}

// NewListIndustryGridSupplyPointsOK creates a ListIndustryGridSupplyPointsOK with default headers values
func NewListIndustryGridSupplyPointsOK() *ListIndustryGridSupplyPointsOK {
	return &ListIndustryGridSupplyPointsOK{}
}

/*
ListIndustryGridSupplyPointsOK describes a response with status code 200, with default header values.

ListIndustryGridSupplyPointsOK list industry grid supply points o k
*/
type ListIndustryGridSupplyPointsOK struct {
	Payload *models.PaginatedGridSupplyPointList
}

// IsSuccess returns true when this list industry grid supply points o k response has a 2xx status code
func (o *ListIndustryGridSupplyPointsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list industry grid supply points o k response has a 3xx status code
func (o *ListIndustryGridSupplyPointsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list industry grid supply points o k response has a 4xx status code
func (o *ListIndustryGridSupplyPointsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list industry grid supply points o k response has a 5xx status code
func (o *ListIndustryGridSupplyPointsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list industry grid supply points o k response a status code equal to that given
func (o *ListIndustryGridSupplyPointsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list industry grid supply points o k response
func (o *ListIndustryGridSupplyPointsOK) Code() int {
	return 200
}

func (o *ListIndustryGridSupplyPointsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/industry/grid-supply-points/][%d] listIndustryGridSupplyPointsOK %s", 200, payload)
}

func (o *ListIndustryGridSupplyPointsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/industry/grid-supply-points/][%d] listIndustryGridSupplyPointsOK %s", 200, payload)
}

func (o *ListIndustryGridSupplyPointsOK) GetPayload() *models.PaginatedGridSupplyPointList {
	return o.Payload
}

func (o *ListIndustryGridSupplyPointsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PaginatedGridSupplyPointList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
