// Code generated by go-swagger; DO NOT EDIT.

package industry

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListIndustryGridSupplyPointsParams creates a new ListIndustryGridSupplyPointsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListIndustryGridSupplyPointsParams() *ListIndustryGridSupplyPointsParams {
	return &ListIndustryGridSupplyPointsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListIndustryGridSupplyPointsParamsWithTimeout creates a new ListIndustryGridSupplyPointsParams object
// with the ability to set a timeout on a request.
func NewListIndustryGridSupplyPointsParamsWithTimeout(timeout time.Duration) *ListIndustryGridSupplyPointsParams {
	return &ListIndustryGridSupplyPointsParams{
		timeout: timeout,
	}
}

// NewListIndustryGridSupplyPointsParamsWithContext creates a new ListIndustryGridSupplyPointsParams object
// with the ability to set a context for a request.
func NewListIndustryGridSupplyPointsParamsWithContext(ctx context.Context) *ListIndustryGridSupplyPointsParams {
	return &ListIndustryGridSupplyPointsParams{
		Context: ctx,
	}
}

// NewListIndustryGridSupplyPointsParamsWithHTTPClient creates a new ListIndustryGridSupplyPointsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListIndustryGridSupplyPointsParamsWithHTTPClient(client *http.Client) *ListIndustryGridSupplyPointsParams {
	return &ListIndustryGridSupplyPointsParams{
		HTTPClient: client,
	}
}

/*
ListIndustryGridSupplyPointsParams contains all the parameters to send to the API endpoint

	for the list industry grid supply points operation.

	Typically these are written to a http.Request.
*/
type ListIndustryGridSupplyPointsParams struct {

	/* Page.

	   A page number within the paginated result set.
	*/
	Page *int64

	/* Postcode.

	   A postcode to filter GSPs by.
	*/
	Postcode *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list industry grid supply points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListIndustryGridSupplyPointsParams) WithDefaults() *ListIndustryGridSupplyPointsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list industry grid supply points params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListIndustryGridSupplyPointsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) WithTimeout(timeout time.Duration) *ListIndustryGridSupplyPointsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) WithContext(ctx context.Context) *ListIndustryGridSupplyPointsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) WithHTTPClient(client *http.Client) *ListIndustryGridSupplyPointsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) WithPage(page *int64) *ListIndustryGridSupplyPointsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) SetPage(page *int64) {
	o.Page = page
}

// WithPostcode adds the postcode to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) WithPostcode(postcode *string) *ListIndustryGridSupplyPointsParams {
	o.SetPostcode(postcode)
	return o
}

// SetPostcode adds the postcode to the list industry grid supply points params
func (o *ListIndustryGridSupplyPointsParams) SetPostcode(postcode *string) {
	o.Postcode = postcode
}

// WriteToRequest writes these params to a swagger request
func (o *ListIndustryGridSupplyPointsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.Postcode != nil {

		// query param postcode
		var qrPostcode string

		if o.Postcode != nil {
			qrPostcode = *o.Postcode
		}
		qPostcode := qrPostcode
		if qPostcode != "" {

			if err := r.SetQueryParam("postcode", qPostcode); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
