// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// CreateAnAccountReader is a Reader for the CreateAnAccount structure.
type CreateAnAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAnAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateAnAccountCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewCreateAnAccountAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateAnAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/accounts/] Create an account", response, response.Code())
	}
}

// NewCreateAnAccountCreated creates a CreateAnAccountCreated with default headers values
func NewCreateAnAccountCreated() *CreateAnAccountCreated {
	return &CreateAnAccountCreated{}
}

/*
CreateAnAccountCreated describes a response with status code 201, with default header values.

Account successfully created
*/
type CreateAnAccountCreated struct {
	Payload *models.SuccessResponse
}

// IsSuccess returns true when this create an account created response has a 2xx status code
func (o *CreateAnAccountCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create an account created response has a 3xx status code
func (o *CreateAnAccountCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create an account created response has a 4xx status code
func (o *CreateAnAccountCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create an account created response has a 5xx status code
func (o *CreateAnAccountCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create an account created response a status code equal to that given
func (o *CreateAnAccountCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create an account created response
func (o *CreateAnAccountCreated) Code() int {
	return 201
}

func (o *CreateAnAccountCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/][%d] createAnAccountCreated %s", 201, payload)
}

func (o *CreateAnAccountCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/][%d] createAnAccountCreated %s", 201, payload)
}

func (o *CreateAnAccountCreated) GetPayload() *models.SuccessResponse {
	return o.Payload
}

func (o *CreateAnAccountCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SuccessResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAnAccountAccepted creates a CreateAnAccountAccepted with default headers values
func NewCreateAnAccountAccepted() *CreateAnAccountAccepted {
	return &CreateAnAccountAccepted{}
}

/*
CreateAnAccountAccepted describes a response with status code 202, with default header values.

The submission has incurred an error, but requires further investigation from a member of our team in order to complete the request.
*/
type CreateAnAccountAccepted struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create an account accepted response has a 2xx status code
func (o *CreateAnAccountAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create an account accepted response has a 3xx status code
func (o *CreateAnAccountAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create an account accepted response has a 4xx status code
func (o *CreateAnAccountAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this create an account accepted response has a 5xx status code
func (o *CreateAnAccountAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this create an account accepted response a status code equal to that given
func (o *CreateAnAccountAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the create an account accepted response
func (o *CreateAnAccountAccepted) Code() int {
	return 202
}

func (o *CreateAnAccountAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/][%d] createAnAccountAccepted %s", 202, payload)
}

func (o *CreateAnAccountAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/][%d] createAnAccountAccepted %s", 202, payload)
}

func (o *CreateAnAccountAccepted) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateAnAccountAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAnAccountBadRequest creates a CreateAnAccountBadRequest with default headers values
func NewCreateAnAccountBadRequest() *CreateAnAccountBadRequest {
	return &CreateAnAccountBadRequest{}
}

/*
CreateAnAccountBadRequest describes a response with status code 400, with default header values.

The submissions incurred validation errors that cannot be fixed by a member of our team. This may occur if the provided reference is a duplicate and the existing enrolment has not previously been rejected.
*/
type CreateAnAccountBadRequest struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this create an account bad request response has a 2xx status code
func (o *CreateAnAccountBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create an account bad request response has a 3xx status code
func (o *CreateAnAccountBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create an account bad request response has a 4xx status code
func (o *CreateAnAccountBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create an account bad request response has a 5xx status code
func (o *CreateAnAccountBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create an account bad request response a status code equal to that given
func (o *CreateAnAccountBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create an account bad request response
func (o *CreateAnAccountBadRequest) Code() int {
	return 400
}

func (o *CreateAnAccountBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/][%d] createAnAccountBadRequest %s", 400, payload)
}

func (o *CreateAnAccountBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/][%d] createAnAccountBadRequest %s", 400, payload)
}

func (o *CreateAnAccountBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *CreateAnAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
