// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// NewCreateAnAccountParams creates a new CreateAnAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateAnAccountParams() *CreateAnAccountParams {
	return &CreateAnAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateAnAccountParamsWithTimeout creates a new CreateAnAccountParams object
// with the ability to set a timeout on a request.
func NewCreateAnAccountParamsWithTimeout(timeout time.Duration) *CreateAnAccountParams {
	return &CreateAnAccountParams{
		timeout: timeout,
	}
}

// NewCreateAnAccountParamsWithContext creates a new CreateAnAccountParams object
// with the ability to set a context for a request.
func NewCreateAnAccountParamsWithContext(ctx context.Context) *CreateAnAccountParams {
	return &CreateAnAccountParams{
		Context: ctx,
	}
}

// NewCreateAnAccountParamsWithHTTPClient creates a new CreateAnAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateAnAccountParamsWithHTTPClient(client *http.Client) *CreateAnAccountParams {
	return &CreateAnAccountParams{
		HTTPClient: client,
	}
}

/*
CreateAnAccountParams contains all the parameters to send to the API endpoint

	for the create an account operation.

	Typically these are written to a http.Request.
*/
type CreateAnAccountParams struct {

	// Body.
	Body *models.Create

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create an account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAnAccountParams) WithDefaults() *CreateAnAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create an account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateAnAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create an account params
func (o *CreateAnAccountParams) WithTimeout(timeout time.Duration) *CreateAnAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create an account params
func (o *CreateAnAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create an account params
func (o *CreateAnAccountParams) WithContext(ctx context.Context) *CreateAnAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create an account params
func (o *CreateAnAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create an account params
func (o *CreateAnAccountParams) WithHTTPClient(client *http.Client) *CreateAnAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create an account params
func (o *CreateAnAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create an account params
func (o *CreateAnAccountParams) WithBody(body *models.Create) *CreateAnAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create an account params
func (o *CreateAnAccountParams) SetBody(body *models.Create) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateAnAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
