// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mgazza/go-octopus-energy/models"
)

// RenewaBusinessTariffReader is a Reader for the RenewaBusinessTariff structure.
type RenewaBusinessTariffReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RenewaBusinessTariffReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRenewABusinessTariffCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRenewABusinessTariffBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewRenewABusinessTariffUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewRenewABusinessTariffForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewRenewABusinessTariffNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRenewABusinessTariffInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/accounts/{account_number}/tariff-renewal/] Renew a business tariff", response, response.Code())
	}
}

// NewRenewABusinessTariffCreated creates a RenewABusinessTariffCreated with default headers values
func NewRenewABusinessTariffCreated() *RenewABusinessTariffCreated {
	return &RenewABusinessTariffCreated{}
}

/*
RenewABusinessTariffCreated describes a response with status code 201, with default header values.

Agreement(s) successfully created
*/
type RenewABusinessTariffCreated struct {
	Payload *models.AgreementsCreated
}

// IsSuccess returns true when this renew a business tariff created response has a 2xx status code
func (o *RenewABusinessTariffCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this renew a business tariff created response has a 3xx status code
func (o *RenewABusinessTariffCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this renew a business tariff created response has a 4xx status code
func (o *RenewABusinessTariffCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this renew a business tariff created response has a 5xx status code
func (o *RenewABusinessTariffCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this renew a business tariff created response a status code equal to that given
func (o *RenewABusinessTariffCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the renew a business tariff created response
func (o *RenewABusinessTariffCreated) Code() int {
	return 201
}

func (o *RenewABusinessTariffCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffCreated %s", 201, payload)
}

func (o *RenewABusinessTariffCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffCreated %s", 201, payload)
}

func (o *RenewABusinessTariffCreated) GetPayload() *models.AgreementsCreated {
	return o.Payload
}

func (o *RenewABusinessTariffCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AgreementsCreated)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRenewABusinessTariffBadRequest creates a RenewABusinessTariffBadRequest with default headers values
func NewRenewABusinessTariffBadRequest() *RenewABusinessTariffBadRequest {
	return &RenewABusinessTariffBadRequest{}
}

/*
RenewABusinessTariffBadRequest describes a response with status code 400, with default header values.

Could not create agreement due to domain or validation errors.
*/
type RenewABusinessTariffBadRequest struct {
	Payload *models.ValidationOrDomainError
}

// IsSuccess returns true when this renew a business tariff bad request response has a 2xx status code
func (o *RenewABusinessTariffBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this renew a business tariff bad request response has a 3xx status code
func (o *RenewABusinessTariffBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this renew a business tariff bad request response has a 4xx status code
func (o *RenewABusinessTariffBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this renew a business tariff bad request response has a 5xx status code
func (o *RenewABusinessTariffBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this renew a business tariff bad request response a status code equal to that given
func (o *RenewABusinessTariffBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the renew a business tariff bad request response
func (o *RenewABusinessTariffBadRequest) Code() int {
	return 400
}

func (o *RenewABusinessTariffBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffBadRequest %s", 400, payload)
}

func (o *RenewABusinessTariffBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffBadRequest %s", 400, payload)
}

func (o *RenewABusinessTariffBadRequest) GetPayload() *models.ValidationOrDomainError {
	return o.Payload
}

func (o *RenewABusinessTariffBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ValidationOrDomainError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRenewABusinessTariffUnauthorized creates a RenewABusinessTariffUnauthorized with default headers values
func NewRenewABusinessTariffUnauthorized() *RenewABusinessTariffUnauthorized {
	return &RenewABusinessTariffUnauthorized{}
}

/*
RenewABusinessTariffUnauthorized describes a response with status code 401, with default header values.

Incorrect authentication.
*/
type RenewABusinessTariffUnauthorized struct {
}

// IsSuccess returns true when this renew a business tariff unauthorized response has a 2xx status code
func (o *RenewABusinessTariffUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this renew a business tariff unauthorized response has a 3xx status code
func (o *RenewABusinessTariffUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this renew a business tariff unauthorized response has a 4xx status code
func (o *RenewABusinessTariffUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this renew a business tariff unauthorized response has a 5xx status code
func (o *RenewABusinessTariffUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this renew a business tariff unauthorized response a status code equal to that given
func (o *RenewABusinessTariffUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the renew a business tariff unauthorized response
func (o *RenewABusinessTariffUnauthorized) Code() int {
	return 401
}

func (o *RenewABusinessTariffUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffUnauthorized", 401)
}

func (o *RenewABusinessTariffUnauthorized) String() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffUnauthorized", 401)
}

func (o *RenewABusinessTariffUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRenewABusinessTariffForbidden creates a RenewABusinessTariffForbidden with default headers values
func NewRenewABusinessTariffForbidden() *RenewABusinessTariffForbidden {
	return &RenewABusinessTariffForbidden{}
}

/*
RenewABusinessTariffForbidden describes a response with status code 403, with default header values.

The user does not have sufficient permissions for this action.
*/
type RenewABusinessTariffForbidden struct {
}

// IsSuccess returns true when this renew a business tariff forbidden response has a 2xx status code
func (o *RenewABusinessTariffForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this renew a business tariff forbidden response has a 3xx status code
func (o *RenewABusinessTariffForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this renew a business tariff forbidden response has a 4xx status code
func (o *RenewABusinessTariffForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this renew a business tariff forbidden response has a 5xx status code
func (o *RenewABusinessTariffForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this renew a business tariff forbidden response a status code equal to that given
func (o *RenewABusinessTariffForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the renew a business tariff forbidden response
func (o *RenewABusinessTariffForbidden) Code() int {
	return 403
}

func (o *RenewABusinessTariffForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffForbidden", 403)
}

func (o *RenewABusinessTariffForbidden) String() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffForbidden", 403)
}

func (o *RenewABusinessTariffForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRenewABusinessTariffNotFound creates a RenewABusinessTariffNotFound with default headers values
func NewRenewABusinessTariffNotFound() *RenewABusinessTariffNotFound {
	return &RenewABusinessTariffNotFound{}
}

/*
RenewABusinessTariffNotFound describes a response with status code 404, with default header values.

The account does not exist.
*/
type RenewABusinessTariffNotFound struct {
}

// IsSuccess returns true when this renew a business tariff not found response has a 2xx status code
func (o *RenewABusinessTariffNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this renew a business tariff not found response has a 3xx status code
func (o *RenewABusinessTariffNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this renew a business tariff not found response has a 4xx status code
func (o *RenewABusinessTariffNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this renew a business tariff not found response has a 5xx status code
func (o *RenewABusinessTariffNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this renew a business tariff not found response a status code equal to that given
func (o *RenewABusinessTariffNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the renew a business tariff not found response
func (o *RenewABusinessTariffNotFound) Code() int {
	return 404
}

func (o *RenewABusinessTariffNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffNotFound", 404)
}

func (o *RenewABusinessTariffNotFound) String() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffNotFound", 404)
}

func (o *RenewABusinessTariffNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRenewABusinessTariffInternalServerError creates a RenewABusinessTariffInternalServerError with default headers values
func NewRenewABusinessTariffInternalServerError() *RenewABusinessTariffInternalServerError {
	return &RenewABusinessTariffInternalServerError{}
}

/*
RenewABusinessTariffInternalServerError describes a response with status code 500, with default header values.

Intermittent internal error. If it persists, please get in touch with the support team.
*/
type RenewABusinessTariffInternalServerError struct {
}

// IsSuccess returns true when this renew a business tariff internal server error response has a 2xx status code
func (o *RenewABusinessTariffInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this renew a business tariff internal server error response has a 3xx status code
func (o *RenewABusinessTariffInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this renew a business tariff internal server error response has a 4xx status code
func (o *RenewABusinessTariffInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this renew a business tariff internal server error response has a 5xx status code
func (o *RenewABusinessTariffInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this renew a business tariff internal server error response a status code equal to that given
func (o *RenewABusinessTariffInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the renew a business tariff internal server error response
func (o *RenewABusinessTariffInternalServerError) Code() int {
	return 500
}

func (o *RenewABusinessTariffInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffInternalServerError", 500)
}

func (o *RenewABusinessTariffInternalServerError) String() string {
	return fmt.Sprintf("[POST /v1/accounts/{account_number}/tariff-renewal/][%d] renewABusinessTariffInternalServerError", 500)
}

func (o *RenewABusinessTariffInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
