// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateQuoteError create quote error
//
// swagger:model CreateQuoteError
type CreateQuoteError struct {

	// brand code
	BrandCode []string `json:"brand_code"`

	// business products only
	BusinessProductsOnly []string `json:"business_products_only"`

	// electricity meter points
	ElectricityMeterPoints []string `json:"electricity_meter_points"`

	// gas meter points
	GasMeterPoints []string `json:"gas_meter_points"`

	// product codes
	ProductCodes []string `json:"product_codes"`
}

// Validate validates this create quote error
func (m *CreateQuoteError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create quote error based on context it is used
func (m *CreateQuoteError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateQuoteError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateQuoteError) UnmarshalBinary(b []byte) error {
	var res CreateQuoteError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
