// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Emails emails
//
// swagger:model Emails
type Emails struct {

	// An array of one or more email addresses to send the email to.
	// Required: true
	Emails []strfmt.Email `json:"emails"`
}

// Validate validates this emails
func (m *Emails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Emails) validateEmails(formats strfmt.Registry) error {

	if err := validate.Required("emails", "body", m.Emails); err != nil {
		return err
	}

	for i := 0; i < len(m.Emails); i++ {

		if err := validate.FormatOf("emails"+"."+strconv.Itoa(i), "body", "email", m.Emails[i].String(), formats); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this emails based on context it is used
func (m *Emails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Emails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Emails) UnmarshalBinary(b []byte) error {
	var res Emails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
