// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Meter meter
//
// swagger:model Meter
type Meter struct {

	// registers
	Registers []*Register `json:"registers"`

	// serial number
	// Example: 1111111111
	SerialNumber string `json:"serial_number,omitempty"`
}

// Validate validates this meter
func (m *Meter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegisters(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Meter) validateRegisters(formats strfmt.Registry) error {
	if swag.IsZero(m.Registers) { // not required
		return nil
	}

	for i := 0; i < len(m.Registers); i++ {
		if swag.IsZero(m.Registers[i]) { // not required
			continue
		}

		if m.Registers[i] != nil {
			if err := m.Registers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("registers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("registers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this meter based on the context it is used
func (m *Meter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRegisters(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Meter) contextValidateRegisters(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Registers); i++ {

		if m.Registers[i] != nil {

			if swag.IsZero(m.Registers[i]) { // not required
				return nil
			}

			if err := m.Registers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("registers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("registers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Meter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Meter) UnmarshalBinary(b []byte) error {
	var res Meter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
