// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PSR p s r
//
// swagger:model PSR
type PSR struct {

	// If true, indicates that the user should be signed up to the PSR but the categories are unknown. Therefore the user requires contacting to determine the categories.
	RequiresSignup bool `json:"requires_signup,omitempty"`
}

// Validate validates this p s r
func (m *PSR) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this p s r based on context it is used
func (m *PSR) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PSR) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PSR) UnmarshalBinary(b []byte) error {
	var res PSR
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
