// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Quote quote
//
// swagger:model Quote
type Quote struct {

	// The estimated annual payment for this meter-point based on consumption.
	//
	// This value must be provided in pence. For business quotes, the price is exclusive of VAT, while for non-business quotes, it should be inclusive of VAT.
	// Required: true
	// Minimum: 0
	AnnualPayment *int64 `json:"annual_payment"`
}

// Validate validates this quote
func (m *Quote) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAnnualPayment(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Quote) validateAnnualPayment(formats strfmt.Registry) error {

	if err := validate.Required("annual_payment", "body", m.AnnualPayment); err != nil {
		return err
	}

	if err := validate.MinimumInt("annual_payment", "body", *m.AnnualPayment, 0, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this quote based on context it is used
func (m *Quote) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Quote) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Quote) UnmarshalBinary(b []byte) error {
	var res Quote
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
