// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Register register
//
// swagger:model Register
type Register struct {

	// identifier
	// Example: 1
	Identifier string `json:"identifier,omitempty"`

	// is settlement register
	// Example: true
	IsSettlementRegister bool `json:"is_settlement_register,omitempty"`

	// rate
	// Example: STANDARD
	Rate string `json:"rate,omitempty"`
}

// Validate validates this register
func (m *Register) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this register based on context it is used
func (m *Register) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Register) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Register) UnmarshalBinary(b []byte) error {
	var res Register
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
