// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SampleQuotes sample quotes
//
// swagger:model SampleQuotes
type SampleQuotes struct {

	// Annual cost (inc or exc)
	// Required: true
	DualFuelDualRate map[string]int64 `json:"dual_fuel_dual_rate"`

	// Annual cost (inc or exc)
	// Required: true
	DualFuelSingleRate map[string]int64 `json:"dual_fuel_single_rate"`

	// Annual cost (inc or exc)
	// Required: true
	ElectricityDualRate map[string]int64 `json:"electricity_dual_rate"`

	// Annual cost (inc or exc)
	// Required: true
	ElectricitySingleRate map[string]int64 `json:"electricity_single_rate"`
}

// Validate validates this sample quotes
func (m *SampleQuotes) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDualFuelDualRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDualFuelSingleRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateElectricityDualRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateElectricitySingleRate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SampleQuotes) validateDualFuelDualRate(formats strfmt.Registry) error {

	if err := validate.Required("dual_fuel_dual_rate", "body", m.DualFuelDualRate); err != nil {
		return err
	}

	return nil
}

func (m *SampleQuotes) validateDualFuelSingleRate(formats strfmt.Registry) error {

	if err := validate.Required("dual_fuel_single_rate", "body", m.DualFuelSingleRate); err != nil {
		return err
	}

	return nil
}

func (m *SampleQuotes) validateElectricityDualRate(formats strfmt.Registry) error {

	if err := validate.Required("electricity_dual_rate", "body", m.ElectricityDualRate); err != nil {
		return err
	}

	return nil
}

func (m *SampleQuotes) validateElectricitySingleRate(formats strfmt.Registry) error {

	if err := validate.Required("electricity_single_rate", "body", m.ElectricitySingleRate); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sample quotes based on context it is used
func (m *SampleQuotes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SampleQuotes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SampleQuotes) UnmarshalBinary(b []byte) error {
	var res SampleQuotes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
