// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ValidationErrors validation errors
//
// swagger:model ValidationErrors
type ValidationErrors struct {

	// emails
	// Required: true
	Emails interface{} `json:"emails"`
}

// Validate validates this validation errors
func (m *ValidationErrors) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ValidationErrors) validateEmails(formats strfmt.Registry) error {

	if m.Emails == nil {
		return errors.Required("emails", "body", nil)
	}

	return nil
}

// ContextValidate validates this validation errors based on context it is used
func (m *ValidationErrors) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ValidationErrors) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ValidationErrors) UnmarshalBinary(b []byte) error {
	var res ValidationErrors
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
